### ISSUE TITLE
[Android] Globe height behaving unexpectedly

### ISSUE THREAD

**Issue by JtxGit** [mousebird/WhirlyGlobe-3#12]
`globeControl.viewState.height`
always seems to return zero

while
`globeControl.positionGeo.z`
returns a value

Should they return the same value?

**Comment by mousebird** [comment]
I'm guessing that's through Kotlin?
Looking at getViewState() in GlobeController, it's making the same calls as getPositionGeo().  The data is just returned differently.

Is it possible you're getting nulls back?

**Comment by JtxGit** [comment]
Kotlin yes.

For some reason, the one always return zero (not null), while the other way always returns a value. Even when called at the same time at the same place in my code.

I will dig a bit more...

**Comment by JtxGit** [comment]
If I look at the method: "getPositionGeo()"
The z-component is taken from "globeView.getLoc().getZ()"

While in the method: "getViewState()"
We first get "globeView.getLoc()"
then convert this to "geoLoc"
then take "geoLoc.getZ()"

To my limited understanding this is not the same thing... Or am I missing something?

**Comment by mousebird** [comment]
That could be the problem.  I'll set up a test tomorrow and see if it is.

**Comment by mousebird** [comment]
Can confirm this was a bug on Android.  Height is now correct coming back from getViewState().  Develop branch.
