### ISSUE TITLE
[Android]  GlobeController setViewState

### ISSUE THREAD

**Issue by JtxGit** [mousebird/WhirlyGlobe-3#13]
Is this height heading interaction intentional?

`		if (viewState.height != Double.MAX_VALUE && !getKeepNorthUp())
			globeView.setHeading(viewState.heading);`

**Comment by mousebird** [comment]
If you have northUp turned on then you can't directly set the heading.  That appears to be correct.

**Comment by JtxGit** [comment]
OK, but why is the "height" value  checked before setting the "heading"?

**Comment by mousebird** [comment]
Oh, I see what you're saying.  Because it's a bug!

**Comment by mousebird** [comment]
Fixed in develop.
