### ISSUE TITLE
[Android] GlobeController setHeading

### ISSUE THREAD

**Issue by JtxGit** [mousebird/WhirlyGlobe-3#14]
Does not seem to actually set the heading?

`	public void setHeading(final double heading)
	{
		if (!isCompletelySetup())
			return;

		globeView.cancelAnimation();
	}`

**Comment by mousebird** [comment]
Are you calling this right as the system is still being set up?  That's what that check is for.

**Comment by JtxGit** [comment]
I must be missing something, but I cannot see that the variable "heading" that is passed into the method "setHeading" is actually used in this method. Why is it passed to the method if it is not used at all? And since the method is called "setHeading", I expected it  to actually set the heading...

**Comment by mousebird** [comment]
In 3.0?  You're right!

**Comment by JtxGit** [comment]
Yes, I'm using 3.0 (develop)

**Comment by mousebird** [comment]
Fixed in develop.
