### ISSUE TITLE
[Android] Point2d 

### ISSUE THREAD

**Issue by JtxGit** [mousebird/WhirlyGlobe-3#15]
Not sure how to troubleshoot this...

This code:
`var ptRad: Point2d`
`ptRad = Point2d.FromDegrees(16.59,59.53)`

causes this error:
`java.lang.UnsatisfiedLinkError: No implementation found for void com.mousebird.maply.Point2d.nativeInit() (tried Java_com_mousebird_maply_Point2d_nativeInit and Java_com_mousebird_maply_Point2d_nativeInit__)
        at com.mousebird.maply.Point2d.nativeInit(Native Method)
        at com.mousebird.maply.Point2d.<clinit>(Point2d.java:133)
        at com.mousebird.maply.Point2d.FromDegrees(Point2d.java:88)`

Any help would be appreciated.

**Comment by mousebird** [comment]
I get things like that if the library has not yet been loaded.  Are you doing this before you starting a Globe or Map controller?

**Comment by JtxGit** [comment]
This is during startup of the activity that hosts the fragment.
Can Point2d only be used after the globe controller is started?

**Comment by mousebird** [comment]
Not exactly.  The C++ library has to be loaded in, but you can force that like so:
			System.loadLibrary("whirlyglobemaply");

**Comment by JtxGit** [comment]
OK, thanks! Will test it now.

**Comment by JtxGit** [comment]
Great! That worked
