### ISSUE TITLE
[Android] Constant tile layer level on Globe possible?

### ISSUE THREAD

**Issue by JtxGit** [mousebird/WhirlyGlobe-3#16]
Is it possible to "lock" or specify a constant tile layer level on the Globe? 
The problem is that while panning around in say the Scandinavia area, the tile layer level would suddenly change, resulting in sudden (quite annoying) changes of visible details.

**Comment by mousebird** [comment]
Heh.  Spherical Mercator.

But maybe, you could specific a tile source with a single level of detail and see what that does.
Is this 3.0?

**Comment by JtxGit** [comment]
Yes, 3.0
Sorry, but unfortunately I do not understand your answer...
The effect can also be seen in the Autotester. Paging Layer

**Comment by mousebird** [comment]
Yup, I'm familiar with the effect.
I'm not sure there's much you can do.  The tiles get smaller as you go north.
