### ISSUE TITLE
[Android] QuadImageLoader draw priority is broken?

### ISSUE THREAD

**Issue by NasH5169** [mousebird/WhirlyGlobe-3#17]
Hi all,

I'm trying to update my code from version 2 to 3.

I have an issue with draw priorities.

In my app, I organize the priorities like this:

10 to 29: Base maps (QuadImageLoader)
30 to 39: Alternate maps (QuadImageLoader too)
40 and more: MarkerInfo, LabelInfo, etc..

If I add a QuadImageLoader to the map, the QuadImageLoader hides my markers even if a set a lower draw priority:

```
QuadImageLoader loader = new QuadImageLoader(params, tileInfo, mapControl);
loader.setBaseDrawPriority(10);
```

Why? :)

**Comment by mousebird** [comment]
QuadImageLoader uses a range of priorities so you need to give it more room.
There's a baseDrawPriority and a drawPriorityPerLevel, which defaults to 1.
It might use as many levels as you have... levels.  So give it at least 100 to work with.  I usually do 1000.

**Comment by NasH5169** [comment]
Ok sorry. It's ok. I have add enough priorities for my base maps.

Thanks!
