### ISSUE TITLE
[Android] Blur effect on QuadImageLoader borders

### ISSUE THREAD

**Issue by NasH5169** [mousebird/WhirlyGlobe-3#18]
Hello Steve,

As I know, it is the last issue with version 3 migration.

When i'm displaying a QuadImageLoader, the borders are "blur".

If the map is alone, it is not very important but if I display a base map **and** a secondary on top, the edges are not clean.

![Screenshot_20200224-160817](https://user-images.githubusercontent.com/6979479/75163794-1caea900-5720-11ea-8e7a-56c734dcca82.png)

![Screenshot_20200224-160805](https://user-images.githubusercontent.com/6979479/75163791-1c161280-5720-11ea-8d10-2675f4d3eed7.png)

**Comment by mousebird** [comment]
It's the lowest resolution tiles beneath the higher.  This is a problem with transparent tiles.
You can turn if off by using setForceMinLevel(false) on the SamplingParams.

**Comment by NasH5169** [comment]
Available with the Android version of the toolkit?

**Comment by mousebird** [comment]
Yes, though it's fairly recent.

**Comment by NasH5169** [comment]
Ok... i must be silly.

I've just pull the develop branch then rebuild an aar.

I see the setForceMinLevel method into the maply code but not when I insert the new aar into my project... 

```
/**
     * If set, we'll always make sure the min level is loaded in
     * to provide some background.  Turn it off for true single level
     * loading.  Not great for basemaps.  On by default.
     */
    public native void setForceMinLevel(boolean force);
```

o_O

**Comment by NasH5169** [comment]
Steve,

Sorry to reply again but after compiling the last develop branch, i've no setForceMinLevel on SamplingParams class... I see this method into the code but the compiled aar does not provide me this method!

It is strange :)

**Comment by NasH5169** [comment]
OK, i've just add the:

`params.setForceMinLevel(false);`

But no effect.

**Comment by NasH5169** [comment]
Hi,

Back (again) on this issue.

In fact, i've found that `setForceMinLevel(false)` works **only** if `setSingleLevel(true)`

If true, this is a break change between WhirlyGlobe 2.x and 3.

With W2.x, I was able to setSingleLevel(false) without the blur effect around the transparent tiles of the mbtiles.

Again, if true, this is a big issue for us.

**Comment by mousebird** [comment]
I don't mind if hobbyists riding free on WhirlyGlobe-Maply.  That's great.  
But if you actually depend on this toolkit for a product that you make money off of, you should be on support.  Contact me at contact@mousebirdconsulting.com and we'll discuss it.
