### ISSUE TITLE
Errors about missing files in the UIKit directory

### ISSUE THREAD

**Issue by zzjiong** [mousebird/WhirlyGlobe-3#2]
<img width="846" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/15756920/71959683-4114fb80-322e-11ea-9e91-d650c86fde6b.png">
<img width="694" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/15756920/71959692-45411900-322e-11ea-9911-07f36e950a6b.png">

I commented out the error part and found that
<img width="796" alt="#import MaplySharedAttributes h" src="https://user-images.githubusercontent.com/15756920/71959709-4f631780-322e-11ea-94dc-aa33172ad71e.png">

I checked the UIKit directory and found only one file
<img width="401" alt="图片" src="https://user-images.githubusercontent.com/15756920/71959834-98b36700-322e-11ea-85c4-c18f34304030.png">

**Comment by mousebird** [comment]
Are you on the latest develop?  That should be fixed.

**Comment by mousebird** [comment]
I see the master branch was behind.  Fixed now.

**Comment by zzjiong** [comment]
Thank you, branch develop is OK!
