### ISSUE TITLE
 (IOS) file not found WhirlyVector.h

### ISSUE THREAD

**Issue by Asha-Pris** [mousebird/WhirlyGlobe-3#20]
I have install pods using this->

pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe-3.git'

WhirlyVector.h file is show in pod but still keep getting error file not found

**Comment by Asha-Pris** [comment]
![Screenshot 2020-05-28 at 12 56 13 PM](https://user-images.githubusercontent.com/47142020/83111734-aafd4700-a0e2-11ea-9adf-714a52d7cf65.png)
![Screenshot 2020-05-28 at 12 55 47 PM](https://user-images.githubusercontent.com/47142020/83111742-ad5fa100-a0e2-11ea-81bb-d019ab164cb9.png)

**Comment by mousebird** [comment]
Somewhere you'll have a <appname>-Bridging-Header.h file.  If you don't, follow the instructions from Apple to create one.
Put #import "MaplyComponent.h" in that file.

**Comment by Asha-Pris** [comment]
![Screenshot 2020-05-29 at 4 13 57 PM](https://user-images.githubusercontent.com/47142020/83251583-6dbeb500-a1c7-11ea-97c0-07d182693b8a.png)


I have done according your suggestion. still not work out for me.

**Comment by mousebird** [comment]
I've updated the tutorial for Cocoapods in the WG-Maply 3.0 docs.
https://mousebird.github.io/WhirlyGlobe-3/tutorial/ios/building_from_cocoapod.html

The rest of the docs are still out of date, but this one is now correct.  I followed the instructions myself and verified that they worked.
