### ISSUE TITLE
Unable to compile from source

### ISSUE THREAD

**Issue by Dazza666** [mousebird/WhirlyGlobe-3#21]
When I attempt to compile the code, I am getting:

```
In file included from blah/libs/WhirlyGlobeMaply/common/WhirlyGlobeLib/src/WhirlyVector.cpp:21:
In file included from blah/libs/WhirlyGlobeMaply/common/WhirlyGlobeLib/include/WhirlyVector.h:25:
In file included from ../../../common/local_libs/eigen/Eigen/Eigen:1:
In file included from ../../../common/local_libs/eigen/Eigen/Dense:1:
In file included from ../../../common/local_libs/eigen/Eigen/Core:463:
../../../common/local_libs/eigen/Eigen/src/Core/CwiseNullaryOp.h:709:69: error: expected expression
template<typename Derived, bool Big = (Derived::SizeAtCompileTime > = 16)>
                                                                    ^
../../../common/local_libs/eigen/Eigen/src/Core/CwiseNullaryOp.h:741:22: error: too few template arguments for class template 'setIdentity_impl'
    return internal::setIdentity_impl<Derived>::run(derived());
                     ^
../../../common/local_libs/eigen/Eigen/src/Core/CwiseNullaryOp.h:710:8: note: template is declared here
struct setIdentity_impl {
```

Am I doing something wrong, this is the master branch, running XCode 11.5. Autotester works ok, I tried cross checking the project to make sure my setup was the same, as far as I can see it is.

**Comment by mousebird** [comment]
Is this with 2.6 or 3.0?

**Comment by Dazza666** [comment]
This is 3.0

**Comment by mousebird** [comment]
If AutoTester is working then it's probably not a compiler issue.
Are you pulling in any other libraries that might have similar names to things in Eigen?

**Comment by Dazza666** [comment]
To my knowledge, no. I am using firebase, but I don't know what lib's that might be using inside.

I say AutoTester is working, it doesn't appear to be any more. I am getting the same issue with that now.

I have tried restarting xcode, a clean/build, removing derived data etc but to no avail.

**Comment by Dazza666** [comment]
If this is of any use, here is the output for that file:

```
CompileC /Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/Objects-normal/x86_64/LineAndPointShadersGLES.o blah/libs/WhirlyGlobeMaply/common/WhirlyGlobeLib/src/LineAndPointShadersGLES.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'WhirlyGlobeMaplyComponent' from project 'WhirlyGlobeMaplyComponent')
    cd blah/libs/WhirlyGlobeMaply/ios/library/WhirlyGlobe-MaplyComponent
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-ios8.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu++11 -stdlib=libc++ -fmodules -gmodules -fmodules-cache-path=/Users/aUser/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/aUser/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=WhirlyGlobeMaplyComponent -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DDEBUG=1 -DDEBUG=1 -DHAVE_PTHREAD=1 -DUNORDERED=1 -DLASZIPDLL_EXPORTS=1 -D__IPHONEOS__ -D__USE_SDL_GLES__ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -fvisibility-inlines-hidden -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -index-store-path /Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Index/DataStore -iquote /Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/WhirlyGlobeMaplyComponent-generated-files.hmap -I/Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/WhirlyGlobeMaplyComponent-own-target-headers.hmap -I/Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/WhirlyGlobeMaplyComponent-all-non-framework-target-headers.hmap -ivfsoverlay /Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/all-product-headers.yaml -iquote /Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/WhirlyGlobeMaplyComponent-project-headers.hmap -I/Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Products/Debug-iphonesimulator/include -I../WhirlyGlobeLib/include -I../../../common/local_libs/eigen -I../../../common/local_libs/proj-4/src -I../../../common/local_libs/KissXML/KissXML -I../../../common/local_libs -I../../../common/local_libs/protobuf/src -Iblah/libs/WhirlyGlobeMaply/ios/library/WhirlyGlobe-MaplyComponent/include/private -Iblah/libs/WhirlyGlobeMaply/ios/library/WhirlyGlobe-MaplyComponent/include/vector_tiles -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/usr/include/libxml2 -Iblah/libs/WhirlyGlobeMaply/ios/library/WhirlyGlobe-MaplyComponent/include -I../../../common/local_libs/SMCalloutView -I../../../common/local_libs/KissXML/KissXML/Additions -I../../../common/local_libs/KissXML/KissXML/Categories -I../../../common/local_libs/KissXML/KissXML/Private -I../../../common/local_libs/fmdb/src/fmdb -I../../../common/local_libs/aaplus -I../../../common/local_libs/laszip/include/laszip -I../../../common/local_libs/octencoding -I../../../common/local_libs/include -I../../../common/local_libs/clipper -I../../../common/local_libs/glues/include -I/Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/DerivedSources-normal/x86_64 -I/Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/DerivedSources/x86_64 -I/Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/DerivedSources -F/Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/Objects-normal/x86_64/LineAndPointShadersGLES.d --serialize-diagnostics /Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/Objects-normal/x86_64/LineAndPointShadersGLES.dia -c blah/libs/WhirlyGlobeMaply/common/WhirlyGlobeLib/src/LineAndPointShadersGLES.cpp -o /Users/aUser/Library/Developer/Xcode/DerivedData/AutoTester-ducwlgyhdfwgghbklxxxomvwvmtj/Build/Intermediates.noindex/WhirlyGlobeMaplyComponent.build/Debug-iphonesimulator/WhirlyGlobeMaplyComponent.build/Objects-normal/x86_64/LineAndPointShadersGLES.o

In file included from blah/libs/WhirlyGlobeMaply/common/WhirlyGlobeLib/src/LineAndPointShadersGLES.cpp:21:
In file included from blah/libs/WhirlyGlobeMaply/common/WhirlyGlobeLib/include/LineAndPointShadersGLES.h:21:
In file included from blah/libs/WhirlyGlobeMaply/common/WhirlyGlobeLib/include/ProgramGLES.h:25:
In file included from blah/libs/WhirlyGlobeMaply/common/WhirlyGlobeLib/include/WhirlyVector.h:25:
In file included from ../../../common/local_libs/eigen/Eigen/Eigen:1:
In file included from ../../../common/local_libs/eigen/Eigen/Dense:1:
In file included from ../../../common/local_libs/eigen/Eigen/Core:463:
../../../common/local_libs/eigen/Eigen/src/Core/CwiseNullaryOp.h:709:69: error: expected expression
template<typename Derived, bool Big = (Derived::SizeAtCompileTime > = 16)>
                                                                    ^
../../../common/local_libs/eigen/Eigen/src/Core/CwiseNullaryOp.h:741:22: error: too few template arguments for class template 'setIdentity_impl'
    return internal::setIdentity_impl<Derived>::run(derived());
                     ^
../../../common/local_libs/eigen/Eigen/src/Core/CwiseNullaryOp.h:710:8: note: template is declared here
struct setIdentity_impl {
       ^
2 errors generated.
```

**Comment by mousebird** [comment]
Is the develop branch any different?

**Comment by Dazza666** [comment]
Ok, so this morning I tried develop, and saw the exact same issue,

Then, I noticed that my uncrustify script was running just before the build and reformatting some of the whirleyglobe files, would you believe whatever it was doing to them was causing the compilation to then fail!

This also explains why the autotester build worked, then didn't! Thanks for your help.

So, I am up and running now, of sorts but am having a couple of issues, namely the map does not appear until I jab at the screen seemingly randomly, then it shows up, but it doesn't appear to rerender itself all the time when I interact with it, and often the touch events appear to be missed, Is there a forum or some documentation for V3.0 somewhere?

For reference, I am creating the map like this, is this correct. It took me a while to realise that I didn't have to add a explicit layer like the documentation for v2 mentions, because the map wasn't appearing for me initially until I interact with the screen I attempted to port the swift code for the autotester app:

`// Create an empty globe and add it to the view
        self.globeViewController = [[WhirlyGlobeViewController alloc] init];
        //self.globeViewController.inScrollView = true;
        [self.mFreeRunMapView addSubview:self.globeViewController.view];

        CGRect newBounds = self.view.bounds;
        newBounds.size.height = newBounds.size.height - 100;

        self.globeViewController.view.frame = newBounds;
        [self addChildViewController:self.globeViewController];

        if ([self.globeViewController isKindOfClass:[WhirlyGlobeViewController class]]) {
            // self.globeViewC = (WhirlyGlobeViewController *)self.globeViewC;
        } else {
            self.mapViewController = (MaplyViewController *)self.globeViewController;
        }

        // we want a black background for a globe, a white background for a map.
        self.globeViewController.clearColor = (self.globeViewController != nil) ? [UIColor blackColor] : [UIColor whiteColor];

        // thirty fps if we can get it  change this to 3 if you find your app is struggling
        self.globeViewController.frameInterval = 2;

        MaplySamplingParams * params = [[MaplySamplingParams alloc] init];
        params.minZoom = 0;
        params.maxZoom = 15;
        params.minImportance = 1024 * 1024;
        params.singleLevel = true;
        params.coordSys = [[MaplySphericalMercator alloc] initWebStandard];

        // set up the data source
        self.maplyMBTileFetcher = [[MaplyMBTileFetcher alloc] initWithMBTiles:@"geography-class_medres"];
        self.maplyQuadImageLoader = [[MaplyQuadImageLoader alloc] initWithParams:params tileInfo:self.maplyMBTileFetcher.tileInfo viewC:self.globeViewController];

        [self.maplyQuadImageLoader setTileFetcher:self.maplyMBTileFetcher];
        [self.maplyQuadImageLoader setBaseDrawPriority:kMaplyImageLayerDrawPriorityDefault];

        // start up over San Francisco, center of the universe
        if (self.globeViewController != nil) {
            self.globeViewController.height = 0.8;
            [self.globeViewController animateToPosition:MaplyCoordinateMakeWithDegrees(-122.4192, 37.7793)
                                                   time:10.0];
        } else {
            self.mapViewController.height = 1.0;
            [self.mapViewController animateToPosition:MaplyCoordinateMakeWithDegrees(-122.4192, 37.7793)
                                                 time:10.0];
        }`

**Comment by mousebird** [comment]
What you describe happens if the user is zoomed out far enough that the map or globe doesn't show up.
To fix it, set params.minImportanceTop = 0
But do that after the line: params.minImportance

**Comment by Dazza666** [comment]
Ok, I did what you suggested and lo and behold, it works. I swapped all the params with the example in the v3 autotester app and that seems to 'feel' a bit better than the one's from the 2.6 tutorial, which makes sense.

So, my ultimate aim was to get some of the open sea map data rendered, now I have the basic geography-class_medres working better, I obtained some of data in mbtiles format from this post:

[https://forum.openseamap.org/viewtopic.php?id=2809](url)

specifically, i've tried

[https://ftp5.gwdg.de/pub/misc/openstreetmap/openseamap/charts/mbtiles/OSM-OpenCPN2-Channel.mbtiles](url) 

&

[https://ftp5.gwdg.de/pub/misc/openstreetmap/openseamap/charts/mbtiles/OSM-OpenCPN2-MagellanStrait.mbtiles](url)

However, when I add that file to the maplyMBTileFetcher, I get nothing. I found a program called maptiler which I was able to open said files, and I can see there is data in it. What am I doing wrong now? I know that mbtiles can hold either raster or vector data; but I don't know how to tell, or if I need to use a different class to load the data.

**Comment by Dazza666** [comment]
Ok, so I downloaded sql lite browser, and opened one of the files, selecting a random entry, I get the following:

<img width="1311" alt="Screenshot 2020-06-04 at 17 04 45" src="https://user-images.githubusercontent.com/5719291/83780790-89bdcd00-a685-11ea-9715-9dfc14cee113.png">

So i'm assuming this is raster data (mbtiles files, as you might have guessed are new to me) unless you tell me otherwise.

Now, one thing that is immediately obvious is the schema appears different between the non working _OSM-OpenCPN2-MagellanStrait_

<img width="1054" alt="Screenshot 2020-06-04 at 17 53 23" src="https://user-images.githubusercontent.com/5719291/83787864-57fc3480-a68c-11ea-8a9d-67bce8a25d63.png">

and the working  _geography-class_medres_

<img width="1049" alt="Screenshot 2020-06-04 at 18 05 16" src="https://user-images.githubusercontent.com/5719291/83788991-fd63d800-a68d-11ea-999e-0b91ebbbbcd9.png">

**Comment by mousebird** [comment]
Geography class is a lot older.
So your question now is where the data is and what zoom levels it covers.
The MBTileFetcher should read that out of the file.

**Comment by Dazza666** [comment]
Indeed. 

So, I can tell you that I tried replacing the call to load OSM-OpenCPN2-MagellanStrait instead of geography-class_medres in the autotester app, to remove any risk of my code messing stuff up.

I got the black screen in autotester as well

bearing in mind this is all new to me, I have opened the _OSM-OpenCPN2-MagellanStrait_ file in sql browser again and can see zoom levels from 16 to 8:

<img width="1049" alt="Screenshot 2020-06-04 at 18 23 47" src="https://user-images.githubusercontent.com/5719291/83790738-90057680-a690-11ea-92b3-803194bf54f4.png">

in autotesters GeographyClass.swift, the params are set as 

```
        params.minZoom = 0
        params.maxZoom = fetcher.maxZoom()
        params.coordSys = MaplySphericalMercator(webStandard: ())
        params.singleLevel = true
```

So I should try setting minZoom to 8?

**Comment by mousebird** [comment]
No, that'll cause other problems, but it does mean you only have imagery in a pretty narrow band, probably in a fairly small location.
So you have to zoom in on the right location.

**Comment by Dazza666** [comment]
Yes, this is correct, these open sea map files are broken up into sections of seaways across the world

So, all I have done is change the animate method to

`globeVC.animate(toPosition: MaplyCoordinateMakeWithDegrees(-70.101479, -54.650212), time: 1.0)`

Which should put me in the correct area, but I still see nothing - when you say zoom, do you mean set the zoom level? If so, how do I do that - I can't see a method on the viewcontroller to say zoom into level 12.

**Comment by mousebird** [comment]
The toolkit uses height.  Just try pinching your way closer.

**Comment by Dazza666** [comment]
Ok, I see height. I changed the value to the result of getZoomLimitsMax/min but nothing changed.

I have also trying pinching inwards and outwards and nothing changes (see using autotester)

Ive left it a couple of seconds to make sure the above animation completes, in case interacting with the map causes the animation to end.

Still just a black void!

**Comment by mousebird** [comment]
When I'm locating these sorts of tiny MBTiles files, I usually go through this kind of thing.

What I'll do to make it easier is put in a basemap.  For example, look at the Stamen example in the AutoTester app.

But if you do, make sure you set the baseDrawPriority on your overlay map to something large so it shows up.

**Comment by Dazza666** [comment]
Ok, I tried a larger area, the north west passage which is quite a large area 

<img width="1049" alt="Screenshot 2020-06-04 at 21 05 16" src="https://user-images.githubusercontent.com/5719291/83805062-19c03e80-a6a7-11ea-8abe-ef9807a78f0f.png">

but, still a blank canvas so to speak, attempting pinching in etc, the magellen straight (shown at the bottom is indeed tiny in comparison )is that what you mean by tiny? Or are we talking about the zoom levels here?

Had a quick look at the stamen watercolor remote, is that the one you were referring to? I can see no reference to loading a base map in there however, it looks like that is loading data from a remote resource?

**Comment by mousebird** [comment]
It's all about the zoom levels.  You need to get to the point where you can see zoom level 8, if that's where your data starts.

Stamen is a basemap.  I find it's useful to put a basemap underneath your insets to help in navigating.

**Comment by Dazza666** [comment]
Does AnimatedBasemapTestCase sort of show me how its done, sans the animation - I basically just create 2 loaders, one with the geography example, and another with the map i'm interested in then set the baseDrawPriority?

What object does baseDrawPriority live in?

Sorry for all the questions, thank you so much for all your support

**Comment by Dazza666** [comment]
Ok. I will give it a go and report back, probably won't be until Monday now however. Thank you so much for your assistance so far.

**Comment by mousebird** [comment]
Yes, the baseDrawPriority should be larger for the second one.

**Comment by Dazza666** [comment]
Morning, right back on this today

I added one of the maps over the geography map, and after zooming in and out a bit I could see the data - marvellous.

So, I think im almost done with the fundamentals now, but I have one last issue -
as I zoom in, by double clicking the mouse on a given point on the map which appears to zoom in a set amount, the maps appear take it in turns to appear, a video illustrates it best:

![map_zoom](https://user-images.githubusercontent.com/5719291/84156568-8d749980-aa61-11ea-8656-40c7a04cecbc.gif)

I want, ideally to only use the basemap when the other data is not present, so once I reach a zoom level where the more detailed map data exists, I no longer want to see the base map rear its head 

I have set the base map to kMaplyMaxDrawPriorityDefault, and my seamap to kMaplyMaxDrawPriorityDefault+1 although I am not sure what effect this has, as if I omit the setting from the sea map the behaviour is identical, it still shows up.

I tried playing with the min and max zoom levels, but this seemed to make things worse.

How do I achieve what I want?

**Comment by mousebird** [comment]
The maps are probably fighting over draw priority.  Make sure the baseDrawPriority values are far apart.  The map needs a range of drawPriority values of its own because it uses different ones depending on the level.  So try at least 1000 apart or so.

**Comment by Dazza666** [comment]
So, I tried kMaplyImageLayerDrawPriorityDefault+1000 on the seamap, no effect - then 5000, then 50000, behaviour was the same as above.

The base map is set to kMaplyImageLayerDrawPriorityDefault

I tried zooming out then slowly moving in to see if that reveals any more clues.

![map2](https://user-images.githubusercontent.com/5719291/84161135-dc70fd80-aa66-11ea-8ed1-a0a0040ebabb.gif)

**Comment by mousebird** [comment]
It kind of looks like there's no tiles for the max zoom level in your inset file.

**Comment by Dazza666** [comment]
Would it be anything to do with the min / max Zoom on the MaplySamplingParams, do I have to do anything different between my base map and the overlaid map?

Or, failing that is a data problem? The fact the the base map appears to cover zoom levels 
0,1,2,3,4,5,6

but my overlay covers 16, 14, 12, 10, 8 but seems to be missing the 15, 13, 11, 9 does that make the base map bleed through?

**Comment by mousebird** [comment]
Your overlay is missing zoom levels?  That's kind of weird.

**Comment by Dazza666** [comment]
Well, I don't know, I assume it is intentional - if I run a little SQL, it tells me this is whats contained in the file, so it looks like they skip every other one, is that unconventional? Is thats what's causing my problem? 

<img width="379" alt="Screenshot 2020-06-09 at 19 45 53" src="https://user-images.githubusercontent.com/5719291/84187426-f07a2680-aa89-11ea-98e2-3ce474dbea07.png">

And if that is causing my problem, how can I sort it? Can I make the zoom confined to a range for example, or could I lock the zoom at level X, or, can I execute some SQL to make the database sequential e.g. 16,15,14,13,12 - or does that = explode

**Comment by mousebird** [comment]
That is pretty weird, I have to say.
Well you could lock in a single zoom level (e.g. 16) just to look at the data.

**Comment by Dazza666** [comment]
So, this isn't something you have seen before then? As I mentioned before, I obtained the map data from the open sea map project, I don't think its a Mickey Mouse outfit!:

[https://ftp5.gwdg.de/pub/misc/openstreetmap/openseamap/charts/mbtiles/]()

Maybe they did it to save space? The other day when I was unable to get anything to show, I put the map on an Android app called locus, the issue didn't seem to exhibit itself there, not sure that means anything though

While locking at a particular zoom level is ok in the short term to play around, it doesn't really work if the user wants to zoom out and go to another location - Is there no way around this you can think of? e.g. can I overide the pinch out gesture & say manually set the zoom to 14, 12? Would that be very janky? 

Or, what happens if the base map didn't have zoom levels 0,1 for example would it then use my overlay file?

**Comment by mousebird** [comment]
It's drawing both maps at the same time, so as long as you tell the system what levels are available  you should see something.

I honestly don't know why they'd skip zoom levels.

**Comment by Dazza666** [comment]
So its looking for zoom level 9 say on the overlay, it can't find it - so it doesn't draw anything, makes sense to me. But what doesn't make sense is why it's then drawing a zoomed in base map, which only goes to 6, because it doesn't have that data either, but its choosing to zoom in on the image it does have, right?

Why is it not doing the same thing for the overlay? I am missing something?

When you say tell the system, are we talking about the minzoom and maxzoom here? If so, I have tried setting the params to say 16/16 or 12/12, in the hope that this would only show the detailed map when I reach this zoom level - but when I do this I get no overlay map at all, likewise if I tell it its min 10 max 12, I get nothing showing up either.

Maybe its a marine thing with the missing zoom levels, I don't know - this marine charting is new to me.

Is my only hope getting hold of some charts with consecutive zoom levels?

**Comment by mousebird** [comment]
WhirlyGlobe-Maply doesn't work in terms of zoom levels.  It's much more flexible.

You're seeing two maps overlaid on each other because two maps are being rendered at whatever their appropriate resolution is for where you're looking and what data they have available.

**Comment by Dazza666** [comment]
Hello, I can't believe it's been over a month. I had to move onto another project for a couple of weeks but back on this now.

I think I have come to the conclusion that using rastor images to do this results in files that are simply too big, so I have spent the last couple of days looking at vector data solutions instead.

I obtained a large vector file of the worlds seas (about 134MB) worth, loading this in took about 3 minutes or so - once it was there it seemed to work quite well, but further research led me onto the best way to do this being vector based mbfiles

fast forward a bit, I have managed to create a .mbtiles file as a vector based tileset from my original shapefile, when I open it in maptiler to check the output, it looks quite good:
 
![maptiler](https://user-images.githubusercontent.com/5719291/87972273-890aba00-cabe-11ea-8912-60e828f3ca9e.gif)

So, I try and load this into maply, and I get something less good

the zoom range of this file is 0 - 9

using autotester > vector MBtiles as my base, with the settings unchanged:

```
        sampleParams.coordSys = MaplySphericalMercator(webStandard: ())
//      sampleParams.minImportance = 1024 * 1024
        sampleParams.singleLevel = true
        sampleParams.coverPoles = false
        sampleParams.edgeMatching = false
        sampleParams.minZoom = 0
        sampleParams.maxZoom = tileFetcher.maxZoom()
```

I get this behaviour:

It looks like the 'low res' data isn't being swapped out for the high res data, but the higher res data does load, and both sets of data live together on screen:

![maply](https://user-images.githubusercontent.com/5719291/87973274-24e8f580-cac0-11ea-8b75-d0c934851bca.gif)

What am I doing wrong?

**Comment by mousebird** [comment]
It looks like the lowest level is always present, a useful default for a lot of cases.  But not this one.
Try sampleParams.forceMinLevel = false

**Comment by Dazza666** [comment]
That did it, it almost looks awesome now!

It looks like there are gridlines added, how do I turn these off? (I promise I am looking through the doc, but I can't see the option)

![image](https://user-images.githubusercontent.com/5719291/88210592-58588b00-cc4c-11ea-9e26-7b7772ce20b0.png)

![image](https://user-images.githubusercontent.com/5719291/88212815-c488be00-cc4f-11ea-895f-b3299a67072e.png)

They don't exist if I open in mapTiler for example:

![image](https://user-images.githubusercontent.com/5719291/88212951-f732b680-cc4f-11ea-81f0-c9e4e63d3f72.png)

**Comment by mousebird** [comment]
That's what's in the data.  Vector tiles usually overlap each other.

You need to set the color to something non-transparent.

**Comment by Dazza666** [comment]
Got it, perfect! It looks amazing, I can't believe how well it works with the amount of detail I have stuffed in there. Im genuinely bowled over. This library is amazing.

I have one more really trivial question, then I think I have enough to start doing some more interesting things with it.

Can I set the 'background' colour of the globe/map e.g atm I have this:

![image](https://user-images.githubusercontent.com/5719291/88214285-d2d7d980-cc51-11ea-96e7-038242037f72.png)

the black void is basically the sea, can I set the colour? If so, how!!

**Comment by mousebird** [comment]
Try setting the clearColor on the map view controller.

**Comment by Dazza666** [comment]
That works, but it also sets the space outside of the globe to blue, is there a way to constrain it to just the 'globe'? Or do I need to add a vector or something to achieve this?

![image](https://user-images.githubusercontent.com/5719291/88216230-be491080-cc54-11ea-9b02-b9bacbf02602.png)

**Comment by mousebird** [comment]
Ah, it's the globe.

There are two solutions to this.  One is to put something underneath the vectors.  Perhaps some sort of image layer.
Another is to use the MapboxVectorInterpreter that renders vector tiles images.  That tends to work better with the globe.

If you're using a Mapbox style sheet, there's an example for doing this in the MapboxKindaMap swift file in the AutoTester for iOS (3.0).  I think the MapboxVectorInterpreter might work with other style delegates, but I don't use it that way so it's hard to be sure.

**Comment by Dazza666** [comment]
when you say image layer, do you mean say a mbtiles file which has a bunch of blue tiles at a really high zoom level? Or is there an image layer class that I can assign an image and throw onto the globe?

Im not quite sure if I will end up with the globe or the 2D view yet, I love the flair of the globe - who doesn't...But the 2d map is probably more practical, as this is for marine so its likely to display data no more than 10 miles or so from the vessels position.

I don't really know what mapbox is! So have no idea about style sheets...I will do some research and look at the sample code.

**Comment by mousebird** [comment]
If you stuck a single blow image in an MBTiles file that contained only level 0 that'd work, yeah.  Clever idea.

**Comment by Dazza666** [comment]
Super, that actually worked better than I ever thought it would - the pale blue is an image based mbtiles file at zoom 0, with just the block colour contained within the 4 images blobs contained within.

![image](https://user-images.githubusercontent.com/5719291/88813740-36fa2080-d1b1-11ea-9edc-657f6d8bdd58.png)

My maps coming along quite nicely as well, thanks!

**Comment by mousebird** [comment]
Nice!
