### ISSUE TITLE
Library not loaded: @rpath/WhirlyGlobeMaplyComponent.framework/WhirlyGlobeMaplyComponent

### ISSUE THREAD

**Issue by radubc** [mousebird/WhirlyGlobe-3#26]
Hello,

I am trying to use WhirlyGlobe in a "Hello Earth" project, and I get this error. The details from Xcode are here:

dyld: Library not loaded: @rpath/WhirlyGlobeMaplyComponent.framework/WhirlyGlobeMaplyComponent
  Referenced from: /private/var/containers/Bundle/Application/70D60E67-48B9-4F70-A88F-D96CB993AE36/HelloEarth.app/HelloEarth
  Reason: image not found

What can I do to fix it?

Thank you.

**Comment by mousebird** [comment]
You need to include WG-Maply as an Embedded Framework.  Look on the General tab of your Project.
