### ISSUE TITLE
(ios) Location Tracking Real Test Case

### ISSUE THREAD

**Issue by radubc** [mousebird/WhirlyGlobe-3#28]
I am trying to show the user's location on the globe and on the map. On the globe, the location marker (blue dot) keeps flashing. If I zoom out, showing a larger portion of the globe, I notice that the location is actually moving left, then starts again from current position and moves left, and so on. On the map, it works fine, but the map takes. 100% of my processor all the time.

Thinking that I've done something wrong, I went to the Autotester. The thing is that the globe on the Autotester does the same thing.

I did my tests on iPad Pro 10.5 and iPhone X. They all act the same.

Can you please help me figure out why the location flickers and how to fix it?

Thank you.

**Comment by mousebird** [comment]
Looks like a coordinate system bug.  Look for a fix in develop next week.

**Comment by radubc** [comment]
Thank you.

**Comment by mousebird** [comment]
I believe this was fixed.
