### ISSUE TITLE
EXC_BAD_ACCESS when showing Vector MBTiles

### ISSUE THREAD

**Issue by dissymmetryoflift** [mousebird/WhirlyGlobe-3#29]
I've got the AutoTester compiled and running. When I run the Vector MBTiles test in either globe or map, the application throws EXC_BAD_ACCESS in MaplyVectorStyle.mm, Line 480.

Seems like dictRef is NULL. 

When I run my own apps with styles I get the same error, regardless of whether I use MaplyVectorStyleSimpleGenerator or my own SLD file.

**Comment by mousebird** [comment]
I just loaded up the current 2.6 master branch and ran the Vector MBTiles test case.  Worked fine.
What branch is this and which repo?

**Comment by mousebird** [comment]
develop works on 3.0 as well.  Maybe you're on the master branch of 3.0.

**Comment by dissymmetryoflift** [comment]
Yep. Master branch of 3.0. Am I jumping the gun?

**Comment by mousebird** [comment]
Try the develop branch.

**Comment by dissymmetryoflift** [comment]
I don't get the error with the develop branch. I'm still having trouble displaying the tiles I've generated via QGIS. Seems unknown geometry types are getting embedded into the tiles somehow. Does anyone know of a decent "how-to" guide when it comes to generating compatible mbtiles for WhirlyGlobe?

**Comment by mousebird** [comment]
Unknown geometry types is a weird one.  Is there some other tool you could use to load these in?  Maybe MapTiler to verify that they're valid?
