### ISSUE TITLE
(iOS) Missing .metal resource in .podspec file

### ISSUE THREAD

**Issue by dragonikpl** [mousebird/WhirlyGlobe-3#3]
I managed to run Whirly 3.0 using your .podspec file (the only change I had to do is comment out `#import "GlobeTapMessage.h"` inside `WhirlyGlobe-umbrella.h` file), but when actually trying to show 3d globe I am receiving a crash inside the file `BasicDrawableInstanceMTL.mm`:
```
-[MTLRenderPipelineDescriptorInternal validateWithDevice:], line 2439: error 'vertexFunction must not be nil.'
-[MTLRenderPipelineDescriptorInternal validateWithDevice:]:2439: failed assertion `vertexFunction must not be nil.'
```

As far as I understand Metal, this means that .metal file was not added to resources. I confirmed that `MTLLibrary` is not being created by trying to run `po [mtlDevice newDefaultLibrary]` and receiving `nil`.

What I think could be done here is to use https://developer.apple.com/documentation/metal/mtldevice/1433431-makelibrary and just provide `.metal` source as a string.

**Comment by dragonikpl** [comment]
I did a test and created in my project my own `.metal` file with contents of your `wkDefaultShaders.metal` + `DefaultShadersMTL.h` (just copy-pasted them) and it works!

![image](https://user-images.githubusercontent.com/2223025/72016149-843d9180-3263-11ea-92b4-5c7c5b25782b.png)

**Comment by mousebird** [comment]
Thanks for the testing.

Precompiled shaders are a big advantage of Metal so I have to give it up.  I'll have to play with this a bit.
