### ISSUE TITLE
AutoTester crash when exiting a test case

### ISSUE THREAD

**Issue by TimSylvester-mousebird** [mousebird/WhirlyGlobe-3#38]
Segfault in JNI code when exiting a test case.

<img width="633" alt="Screen Shot 2020-10-16 at 12 48 54 PM" src="https://user-images.githubusercontent.com/71895881/96304378-d957c200-0fb0-11eb-90c8-a93452a71f9a.png">

**Comment by mousebird** [comment]
Fixed this one.
