### ISSUE TITLE
AutoTester Crash

### ISSUE THREAD

**Issue by TimSylvester-mousebird** [mousebird/WhirlyGlobe-3#39]
Running "Find Height" test case, not sure what I did, just randomly panning/zooming to test something unrelated.

<img width="883" alt="Screen Shot 2020-10-19 at 4 59 54 PM" src="https://user-images.githubusercontent.com/71895881/96524385-f4366a80-122c-11eb-9abd-81e5d06a94f3.png">

**Comment by TimSylvester** [comment]
Resolved in d29387e55185d38e2f79043210ca1f51cae574a1
