### ISSUE TITLE
[Android] MBTileFetcher getting min and max zoom (hard way)

### ISSUE THREAD

**Issue by NasH5169** [mousebird/WhirlyGlobe-3#4]
Hi Steve,

I'm starting a first migration from 2.6 to version 3.

I use some MBTiles files without minZoom and maxZoom values into the metadata table.

There is still the piece of code the get these values by the "hard way".

But it is conditional to minZoom -1 and maxZoom -1: 

https://github.com/mousebird/WhirlyGlobe-3/blob/master/android/library/maply/src/main/java/com/mousebird/maply/MBTileFetcher.java#L170

The hard way will not been triggered because minZoom and maxZoom will be equal to 0 due to:

https://github.com/mousebird/WhirlyGlobe-3/blob/master/android/library/maply/src/main/java/com/mousebird/maply/SimpleTileFetcher.java#L47

Perhaps, the fix will be to check both values equal 0 and not one of them equal -1:

```
// If we did not get a minZoom and maxZoom, we need to get them the hard way
if (minZoom == 0 && maxZoom == 0) {
// ...
}
```

Moving forward into my migration and come back to you!

**Comment by mousebird** [comment]
minZoom and maxZoom == 0 are valid, though.
I've changed the SimpleTileFetcher to set those to -1.
Let me know if that fixes it for you.  develop branch

**Comment by NasH5169** [comment]
Great!

I continue my workaround.
