### ISSUE TITLE
lodepng.h is not found after installing from cocoapods

### ISSUE THREAD

**Issue by audungk** [mousebird/WhirlyGlobe-3#43]

**Comment by mousebird** [comment]
Right, that might happen.  We have an updated cocoapod, but the branch we're working hasn't been integrated yet.
You can back out to an older commit or use the master branch, depending on the repo.

**Comment by audungk** [comment]
Are there any branches recommended as starting point? Master on both v2 and v3 seems to be missing eigen

**Comment by mousebird** [comment]
eigen should be fixed everywhere.  What branch and which repo?

**Comment by audungk** [comment]
WhirlyGlobe 3:

```
Analyzing dependencies
Pre-downloading: `WhirlyGlobe` from `https://github.com/mousebird/WhirlyGlobe-3.git`, branch `master`
Downloading dependencies
Installing FMDB (2.7.5)
Installing KissXML (5.3.1)
Installing SMCalloutView (2.1.5)
Installing WhirlyGlobe (3.0)
Installing eigen (3.2.10)

[!] Error installing eigen
[!] /usr/local/bin/hg clone https://bitbucket.org/eigen/eigen --rev 3.2.10 /var/folders/g8/dcs10zqs26v6vl3wpl60xpqw0000gn/T/d20201103-82613-1omcvq4

abort: HTTP Error 404: Not Found
```

WhirlyGlobe 2.4:
```
audungk@aBookPro MapLibraryTests % pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (2.4.1)
Installing FMDB (2.7.5)
Installing SMCalloutView (2.1.5)
Installing WhirlyGlobe (2.4)
Installing boost (1.51.0)
Installing clipper (6.1.3a)
Installing eigen (3.2.10)

[!] Error installing eigen
[!] /usr/local/bin/hg clone https://bitbucket.org/eigen/eigen --rev 3.2.10 /var/folders/g8/dcs10zqs26v6vl3wpl60xpqw0000gn/T/d20201103-82662-1up2594

abort: HTTP Error 404: Not Found


[!] 'boost' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.
```

**Comment by mousebird** [comment]
For WhirlyGlobe-3 the develop branch should point to the local version of Eigen now.
For the second example, the WhirlyGlobe entry in the Cocoapods is repo is very much out of date.  Wouldn't recommend using it.

**Comment by audungk** [comment]
Building from develop reports the missing lodepng.h error, any suggestion to how far back I would have to go to be able to build?
![Screenshot 2020-11-05 at 15 05 38](https://user-images.githubusercontent.com/150725/98251049-843c1a00-1f78-11eb-9ac8-d3fd5a59021e.png)

**Comment by mousebird** [comment]
The develop on the WhirlyGlobe repo should now be up to date.
We're using Pods on a client project and it appears to work fine there.
