### ISSUE TITLE
(iOS) Metal implementation crashing on Release build

### ISSUE THREAD

**Issue by dragonikpl** [mousebird/WhirlyGlobe-3#5]
I manually built Whirly on a Release configuration into .framework file, but I am having crashes on Metal rendering when playing with the app.
Here is my simple code:
```
import UIKit
import WhirlyGlobeMaplyComponent

class ViewController: UIViewController {

    let whirly = WhirlyGlobeViewController()
    var fetcher: MaplyMBTileFetcher!
    var loader: MaplyQuadImageLoader!
    
    lazy var samplingParams: MaplySamplingParams = {
           let samplingParams = MaplySamplingParams()
           samplingParams.coordSys = fetcher!.coordSys()
           samplingParams.coverPoles = true
           samplingParams.edgeMatching = true
           samplingParams.minZoom = fetcher!.minZoom()
           samplingParams.maxZoom = fetcher!.maxZoom()
           samplingParams.singleLevel = true
           return samplingParams
       }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // setup whirly
        addChild(whirly)
        view.addSubview(whirly.view)
        whirly.didMove(toParent: self)
        whirly.keepNorthUp = true
        
        // setup mbtile
        fetcher = MaplyMBTileFetcher(mbTiles: "geography-class_medres")!
        loader = MaplyQuadImageLoader(params: samplingParams, tileInfo: fetcher.tileInfo(), viewC: whirly)
        loader?.setTileFetcher(fetcher)
    }
}
```

And here are the crashes that I encountered on iPad Air (3rd gen) running 13.2.3:

![Screenshot 2020-01-20 at 16 01 47](https://user-images.githubusercontent.com/2223025/72737273-90005080-3b9f-11ea-9d94-d77490501f53.png)
![Screenshot 2020-01-20 at 15 56 16](https://user-images.githubusercontent.com/2223025/72737274-9098e700-3b9f-11ea-8ab0-41b6175c4fa8.png)
![Screenshot 2020-01-20 at 16 03 32](https://user-images.githubusercontent.com/2223025/72737276-9098e700-3b9f-11ea-8775-be7aec8c8a61.png)
![Screenshot 2020-01-20 at 16 05 42](https://user-images.githubusercontent.com/2223025/72737277-9098e700-3b9f-11ea-9d29-95ace5fbbc21.png)
![Screenshot 2020-01-20 at 16 05 13](https://user-images.githubusercontent.com/2223025/72737279-9098e700-3b9f-11ea-9782-c40f014bbf81.png)
![Screenshot 2020-01-20 at 16 04 24](https://user-images.githubusercontent.com/2223025/72737280-91317d80-3b9f-11ea-83de-6d308da425ce.png)

Let me know if you need any information. I can also send you my compiled .framework or build script that I am using.

**Comment by mousebird** [comment]
Make sure you're on the latest develop.  I've seen some problems with missing data filter all the way down into the renderer.
Are you able to build and run the AutoTester app?

**Comment by dragonikpl** [comment]
I could recreate the same thing on build that uses Cocoapod integration.
![image](https://user-images.githubusercontent.com/2223025/72746861-7bc64e80-3bb3-11ea-902a-788342263348.png)
Crashes from my first post are from latest (todays) `develop` branch, so I assume that's the latest one. Cocoapods build is from 2-3 weeks ago, but I will fetch latest code and see if it can be recreated.
I didn't run AutoTester app - my whole source code is what I posted above.

**Comment by mousebird** [comment]
With Cocoapods, you'll need to pull the .metal shaders in to your app directly.  At present, the podspec isn't picking up the shaders for inclusion.

Are you running on the simulator or a device and do you see a difference between debug and release?

If the AutoTester app is working but your code isn't that suggests a configuration problem or possibly missing data not being caught before the rendering step.

**Comment by dragonikpl** [comment]
Maybe you misunderstood me a little - application runs, I can interact with it, but it crashes after few minutes of working on it.
But I think I found the issue: if I set in target scheme flag to disable `Metal API Validation` then it doesn't crash at all.
My assumption would be correct, as I cannot crash application run from iPad, but can always crash when starting it from Xcode and having the flag enabled.

Tested on latest `develop` branch with cocoapods setup.
Up to you to close it, we will just disable this flag.

**Comment by mousebird** [comment]
Ah yes, the Metal API Validation layer does cause some odd problems at times.
It's good for catching things quickly, but the longer you run it the higher possibility of a crash.

I haven't seen any real crashes in deployed apps that would indicate the layer is telling me something.  But we'll see.

**Comment by mousebird** [comment]
Having spent a lot more time with the Metal API validation layer, ya gotta turn it off for regular use.  It's a teeny bit flakey.
