### ISSUE TITLE
(iOS) Latest develop doesn't work on iOS simulator

### ISSUE THREAD

**Issue by dragonikpl** [mousebird/WhirlyGlobe-3#6]
I am using cocoapods setup with latest `develop` branch and when trying to run on iOS simulator I am getting flood of error messages:
`[CAMetalLayer nextDrawable] returning nil because device is nil.`
Nothing is being shown on screen (black screen). When running on physical device everything works as intended.

Tested on `Xcode 11.2.1` and two different simulators: `iPad Pro (3rd gen)` and `iPad Air (3rd gen)` running `iOS 13.2.2`

**Comment by NasH5169** [comment]
Hi,

Same here.

Lastest develop.

Framework built with buildframework.sh

**Comment by mousebird** [comment]
The simulator is still a bit touchy.  You need to have the very latest version of Mac OS as well.
So I'm going to put simulator issues aside fro now.

**Comment by mousebird** [comment]
Works pretty well on the latest version of MacOS.  I'm seeing a little flakiness in Mapbox Style Sheet rendering, but let's open up a separate Issue for that.
