### ISSUE TITLE
(iOS) MaplyScreenLabel text justify issues

### ISSUE THREAD

**Issue by dragonikpl** [mousebird/WhirlyGlobe-3#9]
Tested on latest develop using cocoapods.

Test code:
```
    let location = MaplyCoordinate(x: 0.2, y: 0.2)
    let marker = MaplyScreenMarker()
    marker.image = UIImage(named: "blue-oval")
    marker.loc = location
    whirly.addScreenMarkers([marker], desc: nil)

    let label = MaplyScreenLabel()
    label.text = "Hello World"
    label.loc = location
    let labelSettings: [String: Any] = [
        kMaplyFont: UIFont.systemFont(ofSize: 12),
        kMaplyTextColor: UIColor.red,
        kMaplyJustify: kMaplyTextJustifyCenter
    ]
    whirly.addScreenLabels([label], desc: labelSettings)

    whirly.setPosition(location, height: 0.5)
```

These are the results when changing `kMaplyJustify` to different options:
`kMaplyTextJustifyLeft`:
![image](https://user-images.githubusercontent.com/2223025/72806582-c39db200-3c55-11ea-9ba0-310c81a65ea1.png)
`kMaplyTextJustifyRight`:
![image](https://user-images.githubusercontent.com/2223025/72806611-d1ebce00-3c55-11ea-881d-1df9f9bee5ca.png)
`kMaplyTextJustifyCenter`:
![image](https://user-images.githubusercontent.com/2223025/72806644-e039ea00-3c55-11ea-9d46-19628e8e3277.png)

As you can see, option `kMaplyTextJustifyCenter` doesn't work properly (doesn't center text to middle)

**Comment by mousebird** [comment]
Should be fixed in 3.0
